### ISSUE TITLE
Questions on merge and rebase

### ISSUE THREAD

**Issue by ddddkim0525** [hkpeterpeter/COMP3111-Spring2018-ProjectBaseCode#10]
In the eclipse IDE, I usually use merge to update my branch to the current master branch. Rebase seems to be doing the same thing, and I'm confused with the difference between the two. Further more, if I want to send a merge pull request from the eclipse IDE, do I use Push to Upstream?

**Comment by hkpeterpeter** [comment]
Instead of merging 2 branches directly, pull request in GitHub is a better (and more systematic way). It will be covered in the next lab. You can read it in advance as all lab materials are uploaded. Rebase is a bit different thing. You can check out the detailed description online: https://git-scm.com/docs/git-rebase
