### ISSUE TITLE
Criteria for "meaningful" and "best" for activity 2

### ISSUE THREAD

**Issue by ddddkim0525** [hkpeterpeter/COMP3111-Spring2018-ProjectBaseCode#11]
What does it mean to be the most meaningful commit and best pull request? Is it about the quantity, elegance of code, number of debugging done? If a team does a gradual development, wouldn't that make each commit similar in size?

**Comment by hkpeterpeter** [comment]
As each student is responsible for 2 features. If all 6 features are correctly implemented, and the students follow the good practice of coding via GitHub (Instead of sharing source code via whatsapp/FB), a student should have no problems to identify the best 3 commits and the best pull request. 

Bad commit example: Fix a typo in README. Change a variable type from int to float. 
Good commit example: Implement a csv import without missing data handling.
